### ISSUE TITLE
Compatibility with drafter 4.0.0-pre.0

### ISSUE THREAD

**Issue by chris48s** [kylef/draughtsman#1]
Hello again :wave:

I've compiled drafter 4.0.0-pre.0 from source as mentioned in https://github.com/apiaryio/drafter/issues/542#issuecomment-387709629 Draughtsman works as documented with drafter 3.2.7, but I'm now getting some errors with the new version e.g:

```python
>>> from draughtsman import parse
>>> parse('# My API')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/stuff/lib/python3.5/site-packages/draughtsman/__init__.py", line 39, in parse
    return deserialiser.deserialise(string)
  File "/path/to/stuff/lib/python3.5/site-packages/refract/json.py", line 145, in deserialise
    return self.deserialise_dict(json.loads(element_json))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```python
>>> from draughtsman import parse
>>> bp = """
... FORMAT: 1A
... 
... # My API
... """
>>> parse(bp)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/stuff/lib/python3.5/site-packages/draughtsman/__init__.py", line 37, in parse
    string = ffi.string(output[0]).decode('utf-8')
  File "/path/to/stuff/lib/python3.5/site-packages/cffi/api.py", line 309, in string
    return self._backend.string(cdata, maxlen)
RuntimeError: cannot use string() on <cdata 'char *' NULL>
```

Seems like maybe the first one is related to the new Refract 1.0 JSON Serialisation format ? Not so sure about the second..

**Comment by kylef** [comment]
Hi @chris48s,

The library currently requires Drafter 3 as the Drafter 4 public interface has changed. There is a fork (https://github.com/mitsuse/draughtsman/commit/7acf56b3b2cea542676623647e114dd227f15f2d) which has some updates for the pre-release. There are also changes in the Refract 1.0 serialisation format that will need to be made in refract.py.

Unfortunately I'm pretty busy right now so I don't have time to work on this. There will be a second Drafter 4.0.0 pre-release hopefully early next week and then we can update draughtsman to support it

**Comment by chris48s** [comment]
Thanks for the info.

> Unfortunately I'm pretty busy right now so I don't have time to work on this

No problem. I'm not in a big rush to start using the pre-release version. At the moment I'm just investigating what I will need to do to support Drafter 4. I will have a look at applying the commit you've linked locally and do some testing.

Once you get round to updating these bindings, do you plan that the 0.2 release will retain backwards-compatibility with Drafter 3, or is draughtsman 0.2 likely to support Drafter 4 only?

**Comment by kylef** [comment]
@chris48s master draughtsman now contains support for Drafter (4.1.0), if you're using Homebrew you'll need to install the formula from https://github.com/Homebrew/homebrew-core/pull/47319 as it's not yet merged.

**Comment by chris48s** [comment]
Thanks for the update. I had a go with the latest code from `master` and drafter 4.1.0 but I'm still seeing similar behaviour.

I've set up a repo with a travis build which installs drafter from https://github.com/apiaryio/drafter/releases/download/v4.1.0/drafter-4.1.0.tar.gz and draughtsman from `git+git://github.com/kylef/draughtsman.git@master` and runs `draughtsman.parse()` on a trivial input which reproduces the issue:

https://github.com/chris48s/draughtsman-minimal-repro/blob/master/.travis.yml
https://travis-ci.org/chris48s/draughtsman-minimal-repro/builds/619336751

**Comment by kylef** [comment]
I've made 044c3f7 which should fix that problem, I also want to get https://github.com/kylef/draughtsman/issues/4 solved so that all supported major versions of Drafter can be tested properly to stop this thing going released in broken state like you've discovered.

**Comment by kylef** [comment]
Draughtsman is working on macOS and ArchLinux in my manual testing with Drafter 4.1.0, I've also setup GitHub actions to test this too (https://github.com/kylef/draughtsman/runs/536904592)

**Comment by chris48s** [comment]
Great - thanks  I haven't investigated in any detail, but I updated my minimal example to pull in `draughtsman==0.2.0` and the build passes :heavy_check_mark:
